export const Messages = {
  DATA_FOUND: 'Data Found',
  DATA_NOT_FOUND: 'Data Not Found',
  CREATE_SUCCESS: 'Created Successfully',
  UPDATED_SUCCESS: 'Updated Successfully',
  INVALID_REQUEST: 'Invalid Request',
  ACTIVATED: 'Activated Successfully',
  DEACTIVATED: 'De-activated Successfully',
  EMAIL_EXISTS: 'Email already exists',
  EMAIL_NOT_FOUND: 'Email Address Not Found',
  USER_NOT_ACTIVE: 'User Not Activated',
  ATTACHED_SUCCESS: 'Attached Successfully',
  REMOVED_SUCCESS: 'Removed Successfully',
  DELETED_SUCCESS: 'Deleted Successfully',
  UPLOAD_SUCCESS: 'Uploaded successfully',
  REQUIRED_KEY: 'Key should not be empty',
  REQUIRED_IMG_NAME: 'Image name should not be empty',
  KEY_ALREADY_EXISTS: 'Key already exists',
  ORGANISATION_EXISTS: 'Organisation Name Already Exists',
  DOMAIN_EXISTS: 'Domain Name Already Exists',
  CLIENT_NOT_FOUND: 'Client Not Found',
  INVITE_SENT_SUCCESS: 'Invite Sent Successfully',
  CURRENCY_NOT_FOUND: 'Currency Not Found',
};
